name: Publish GoogleAPI Library

on:
  release:
    types: [published]

defaults:
  run:
    shell: bash

permissions:
  id-token: write

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  publish:
    name: 'Publish: Bun Registry'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          registry-url: "https://registry.npmjs.org"

      - name: Install Build tool Dependencies
        run: bun add -D @types/bun bun-plugin-dts

      - name: Build the project
        run: bun build.ts

      - name: Remove Build tool Dependencies
        run: bun remove @types/bun bun-plugin-dts

      - name: Publish to NpmJS using Bun
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --provenance --access=public
